### PR TITLE
#6597 Rating Scale with the Dropdown display mode- A selected value disappears when the Rating is in a drop-down mode

### LINKED ISSUE #6597: Rating Scale with the Dropdown display mode- A selected value disappears when the Rating is in a drop-down mode
[View Demo](https://plnkr.co/edit/jYICF67pUeUjedbq)

To reproduce the issue, run [the Rating Scale demo](https://surveyjs.io/form-library/examples/ui-adaptation-modes-for-rating-scale/reactjs). Test a Rating Scale in a mobile mode (or set `displayMode: "dropdown") and select a value. 
image

Activate a drop-down again and notice that the selected value disappears.
image

### PR DESCRIPTION
**Pull request by novikov82**
Fixes #6597

### CODE REVIEW

File: src/question_rating.ts [hunk 1]
```diff
@@ -173,6 +173,15 @@ export class QuestionRatingModel extends Question {
       });
   }
 
+  @property({ defaultValue: false }) inputHasValue: boolean;
+
+  public get showSelectedItemLocText(): boolean {
+    return !this.readOnly && !this.inputHasValue && !!this.selectedItemLocText;
+  }
+  public get selectedItemLocText(): LocalizableString {
```
Comment (andrewtelnov) [inline src/question_rating.ts:181]: Can it return empty array?

Comment (novikov82) [reply src/question_rating.ts:181]: `this.visibleRateValues.filter(v => v.value == this.value)[0]?.locText`
this code is safe, zero element of empty array returns undefined, `?.` protects of reading `locText` for undefined object

**Review by andrewtelnov — APPROVED** [review]
