### PR TITLE
Fix try to set 'passed' when currentPage is undefined. Fix onCurrentP…

### LINKED ISSUE #10893: TypeError: Cannot set properties of undefined (setting 'passed')
T26328 - Cannot complete form when this event is active
https://surveyjs.answerdesk.io/internal/ticket/details/T26328

```
.webcontainer@runtime.e5af05b3.js:26 ERROR TypeError: Cannot set properties of undefined (setting 'passed')
    at _SurveyModel.doCurrentPageCompleteCore (survey-core.mjs:42154:30)
    at doFunc (survey-core.mjs:41804:22)
    at _SurveyModel.validateOnNavigate (survey-core.mjs:41818:17)
    at _SurveyModel.doCurrentPageComplete (survey-core.mjs:42148:21)
    at _SurveyModel.tryComplete (survey-core.mjs:42076:14)
    at survey-core.mjs:40181:70
    at SurveyTaskManagerModel.waitAndExecute (survey-core.mjs:34162:13)
    at _Action.action (survey-core.mjs:40181:44)
    at SurveyNavigationButton_input_0_Template_input_click_0_listener (survey-angular-ui.js:4656:42)
    at executeListenerWithErrorHandling (_debug_node-chunk.mjs:7956:12)
```
﻿

### PR DESCRIPTION
**Pull request by MarchTokenda**
…ageChanged and onCurrentPageChanging calls when handler is async fix #10893

### CODE REVIEW

File: packages/survey-core/tests/surveyShowPreviewTests.ts [hunk 1]
```diff
@@ -3,6 +3,7 @@ import { surveyLocalization } from "../src/surveyStrings";
 import { PanelModel } from "../src/panel";
 import { settings } from "../src/settings";
 import { setOldTheme } from "./oldTheme";
+import { set } from "lodash";
```
Comment (andrewtelnov) [inline packages/survey-core/tests/surveyShowPreviewTests.ts]: Please remove this line

**Review by andrewtelnov — APPROVED** [review]
