### PR TITLE
[Vue3] The Header is not rendered when a survey is loaded asynchronously within the `onMounted` hook

### LINKED ISSUE #9678: [Vue3] The Header is not rendered when a survey is loaded asynchronously within the `onMounted` hook
A reproducible demo is available in a user's ticket at [T22661 - SurveyJS Header Fails to Render When Loading Survey JSON Asynchronously via fromJSON in Vue3](https://surveyjs.answerdesk.io/internal/ticket/details/T22661).

A form header is loaded correctly when it's loaded synchronously: [View Demo](https://codesandbox.io/p/sandbox/surveyjs-library-vue3-forked-92jpdt?file=%2Fsrc%2FApp.vue%3A10%2C1).
Image

However, the header is not rendered when a survey is loaded within the `onMounted` function:
Image

### PR DESCRIPTION
**Pull request by tsv2013**
Fixes #9678

### CODE REVIEW

File: packages/survey-core/tests/surveytests.ts [hunk 1]
```diff
@@ -21979,3 +21979,13 @@ QUnit.test("Don't rise onPageAdded when mooving question", function (assert) {
   assert.equal(pageAddedRaisedCount, 0, "onPageAdded is not raised");
   assert.equal(survey.pages[0].name, "page2", "page2 is the first page");
 });
+
+QUnit.only("Update hasTitle on load from JSON", function (assert) {
```
Comment (OlgaLarina) [inline packages/survey-core/tests/surveytests.ts:21983]: Need to delete "only"

Comment (tsv2013) [reply packages/survey-core/tests/surveytests.ts:21983]: Thank you so much!

**Review by OlgaLarina — APPROVED** [review]
