### PR TITLE
Questions within Custom Components do not display survey variable val…

### LINKED ISSUE #7640: Questions within Custom Components do not display survey variable values
User issue and demo: T16309 - custom Component: title with variables do not work
https://surveyjs.answerdesk.io/internal/ticket/details/T16309

### PR DESCRIPTION
**Pull request by andrewtelnov**
…ues fix #7640

### CODE REVIEW

File: src/question_custom.ts [hunk 1]
```diff
@@ -660,7 +660,8 @@ export class QuestionCustomModel extends QuestionCustomModelBase {
     return this.contentQuestion;
   }
   protected getDefaultTitle(): string {
-    if(this.hasJSONTitle && this.contentQuestion) return this.contentQuestion.title;
+    if(this.hasJSONTitle && this.contentQuestion)
```
Comment (novikov82) [inline src/question_custom.ts:663]: Could you add brackets { } to avoid mistakes in future?

**Review by novikov82 — APPROVED** [review]
