### PR TITLE
Dynamic Matrix - The Remove row button doesn't appear when enabling t…

### LINKED ISSUE #5533: Dynamic Matrix - The Remove row button doesn't appear when enabling the options.allow in the onMatrixAllowRemoveRow event handler
The [onMatrixAllowRemoveRow](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model#onMatrixAllowRemoveRow) event should enable the Remove button for specific dynamic matrix rows depending on a row value. Unfortunately, this function doesn't work: the Remove button doesn't appear for a newly added row: [example](https://plnkr.co/edit/xR76Hqx59amJpzJn).
```
survey.onMatrixAllowRemoveRow.add(function(sender, options) {        
        options.allow = options.row.isEmpty;               
});
```
Original issue: [T11803 - onMatrixAllowRemoveRow does not work](https://surveyjs.answerdesk.io/internal/ticket/details/T11803).

### PR DESCRIPTION
**Pull request by andrewtelnov**
…he options.allow in the onMatrixAllowRemoveRow event handler fixed #5533

### CODE REVIEW

File: src/question_matrixdropdownrendered.ts [hunk 1]
```diff
@@ -411,17 +411,18 @@ export class QuestionMatrixDropdownRenderedTable extends Base {
...
-          break;
-        }
-      }
+      this.hasActionCellInRowsValues[location] = this.hasActionsCellInLocaltion(location);
     }
     return this.hasActionCellInRowsValues[location];
   }
+  private hasActionsCellInLocaltion(location: "start" | "end"): boolean {
+    if(location == "end" && this.hasRemoveRows) return true;
+    var rows = this.matrix.visibleRows;
```
Comment (OlgaLarina) [inline src/question_matrixdropdownrendered.ts:420]: small refactoring: replace 420-424 lines with one
return this.matrix.visibleRows.some((row, index) => !this.isValueEmpty(this.getRowActions(index, location)));

File: tests/question_matrixdynamictests.ts [hunk 2]
```diff
@@ -19,6 +19,7 @@ import { SurveyElement } from "../src/survey-element";
 import { Action } from "../src/actions/action";
 import { MatrixDropdownColumn, matrixDropdownColumnTypes } from "../src/question_matrixdropdowncolumn";
 import { QuestionMatrixDropdownRenderedRow } from "../src/question_matrixdropdownrendered";
+import { AssertionError } from "assert";
```
Comment (OlgaLarina) [inline tests/question_matrixdynamictests.ts:22]: unnecessary import AssertionError

**Review by OlgaLarina — APPROVED** [review]
